CREATE OR REPLACE TABLE `dmp-sandbox-project.dmp_sandbox.raw_shopify_orders` AS
WITH orders AS (
  SELECT 1 AS order_id, DATE_SUB(CURRENT_DATE(), INTERVAL 13 DAY) AS order_date, 100.00 AS revenue UNION ALL
  SELECT 2, DATE_SUB(CURRENT_DATE(), INTERVAL 12 DAY), 75.00 UNION ALL
  SELECT 3, DATE_SUB(CURRENT_DATE(), INTERVAL 11 DAY), 250.00 UNION ALL
  SELECT 4, DATE_SUB(CURRENT_DATE(), INTERVAL 10 DAY), 125.00 UNION ALL
  SELECT 5, DATE_SUB(CURRENT_DATE(), INTERVAL 9 DAY), 50.00 UNION ALL
  SELECT 6, DATE_SUB(CURRENT_DATE(), INTERVAL 8 DAY), 90.00 UNION ALL
  SELECT 7, DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY), 60.00 UNION ALL
  SELECT 8, DATE_SUB(CURRENT_DATE(), INTERVAL 6 DAY), 120.00 UNION ALL
  SELECT 9, DATE_SUB(CURRENT_DATE(), INTERVAL 5 DAY), 200.00 UNION ALL
  SELECT 10, DATE_SUB(CURRENT_DATE(), INTERVAL 4 DAY), 300.00 UNION ALL
  SELECT 11, DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY), 180.00 UNION ALL
  SELECT 12, DATE_SUB(CURRENT_DATE(), INTERVAL 2 DAY), 140.00 UNION ALL
  SELECT 13, DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY), 95.00 UNION ALL
  SELECT 14, CURRENT_DATE(), 220.00
)
SELECT * FROM orders;
